config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

   root 'static_pages#home'
   resources :items do
    collection do
     get 'search'
    end
   end
   
   resources :users
    get    '/login',   to: 'sessions#new'
    post   '/login',   to: 'sessions#create'
    delete '/logout',  to: 'sessions#destroy'

   resources :basket_items, only: [:create, :index, :destroy] 
   
   get '/basket', to: 'basket_items#index'
   
   resources :quotes, only: [:index, :create, :destroy]
   
   resources :bookmarks
 
 #  get '/search', to: 'search#run'
end

app/controllers/basket_items_controller.rb
class BasketItemsController < ApplicationController
    
  def index
    if session[:items_in_basket].nil?
      flash[:danger] = "Basket is empty."
      redirect_to basket_items_path
    else
      @basket_items = Item.find(session[:items_in_basket])
      @basket_items ||= Array.new
    end
    
   
    
  end
    
  def create
    item_id = params[:item_id]
    @item = Item.find(item_id)
    @items_in_basket = session[:items_in_basket]
    @items_in_basket ||= Array.new
    @items_in_basket.push(@item.id)
    session[:items_in_basket] = @items_in_basket
    flash[:info] = "Item added to basket."
    
  end
    
  def destroy 
    #reset_session
    #item.delete
   
    # session[:items_in_basket].find(params[:basket_item])
    #session[:items_in_basket].delete(params[:id])
    # binding.pry
  
    session[:items_in_basket].delete_if{|x| x == params[:basket_item].to_i}
  #  session.delete(basket_item.id)
    flash[:danger] = "Item deleted."
    redirect_to basket_items_path
    flash[:danger] = "Basket is empty." if session[:items_in_basket].blank?
  end
    
  
    
end

app/helpers/basket_items_helper.rb
module BasketItemsHelper
    def empty_whole_basket
        
        
    end
end

app/views/basket_items/index.html.erb
<h1>Basket</h1>

<% %>
<div class="card" style="width: 18rem;">
    
    
  <div class="card-body">
    <% @basket_items.each do |basket_item| %>
    <p class="card-text"> <%= basket_item.id %></p>
    <h5 class="card-title"><%= basket_item.name %></h5>
    <p class="card-text">£ <%= basket_item.price %></p>
     <%= link_to 'Destroy', basket_item_path(@basket_items, {basket_item: basket_item.id}), method: :delete%> 
    <% end %>
   
  </div>
  
 
  
  
  
</div>