config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

   root 'static_pages#home'
   resources :items do
    collection do
     get 'search'
    end
   end
   
   resources :users
    get    '/login',   to: 'sessions#new'
    post   '/login',   to: 'sessions#create'
    delete '/logout',  to: 'sessions#destroy'

   resources :basket_items, only: [:create, :index, :destroy] 
   
   get '/basket', to: 'basket_items#index'
   
   resources :quotes, only: [:index, :create, :destroy]
   
   resources :bookmarks
 
 #  get '/search', to: 'search#run'
end

app/models/user.rb
class User < ApplicationRecord
    has_many :item
    validates_uniqueness_of :username
    validates :username, presence: true, length: { maximum: 25 }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    def new
      @user = User.new
    end
    
    def create
      @user = User.new(user_param)
      if @user.save
        flash[:success] = "Yey, you signed up."
        log_in(@user)
        redirect_to @user
      else
        render 'new'
      end
    end
    
    def index
     
    end
    
    def show
       @user = User.find(params[:id])
      # @items = @user.items 
    end
    
   
    
  private

    def user_param
      params.require(:user).permit(:username)
    end
    
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    
    <%= form_for(@user, url: users_path) do |f| %>
      <%= render 'shared/error_messages', obj: @user %>
      
      <%= f.label :username %>
      <%= f.text_field :username, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<h1> User <%=@user.id%> </h1>
<center><h3>username: <%= @user.username%></h3></center>