config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

   root 'static_pages#home'
   resources :items do
    collection do
     get 'search'
    end
   end
   
   resources :users
    get    '/login',   to: 'sessions#new'
    post   '/login',   to: 'sessions#create'
    delete '/logout',  to: 'sessions#destroy'

   resources :basket_items, only: [:create, :index, :destroy] 
   
   get '/basket', to: 'basket_items#index'
   
   resources :quotes, only: [:index, :create, :destroy]
   
   resources :bookmarks
 
 #  get '/search', to: 'search#run'
end

app/models/item.rb
class Item < ApplicationRecord

  validates :name, presence: true, length: { maximum: 50 }
  validates :price, presence: true
  validate :integer?
  
  def integer?
      unless price.to_i.positive?
          errors.add(:price, "should be a valid number")
      end
  end
  
  def self.visible
      where(hidden: false)
  end
  
 
  # def self.search_all_parameters(search_params)
  #   Item.where('name LIKE ? AND price BETWEEN ? AND ?',"%#{search_params[:name].downcase}%" ,search_params[:min],search_params[:max])
  # end
   #Everything is given for the search
  scope :search_all_parameters, ->(search_params) {where('name LIKE ? AND price BETWEEN ? AND ?',"%#{search_params[:name].downcase}%" ,search_params[:min],search_params[:max]) }

  scope :min_max, ->(search_params) {where('price BETWEEN ? AND ?',search_params[:min],search_params[:max])}

  scope :name_search, ->(search_params) {where('name LIKE ?', "%#{search_params[:name].downcase}%")}
  
  scope :max_margin, ->(search_params) {where('name LIKE ? AND price <= ?',"%#{search_params[:name].downcase}%", search_params[:max])}
  
  scope :min_margin, ->(search_params) {where('name LIKE ? AND price >= ?',"%#{search_params[:name].downcase}%", search_params[:min])}
  



  def perform_search(search_params)
   # binding.pry
        if all_present?
          Item.search_all_parameters(search_params)
          
        elsif min_max_values_present?
          Item.min_max(search_params)

        elsif name_value_present?
          Item.name_search(search_params)
          
        elsif name_max_values_present?
          Item.max_margin(search_params)
          
        elsif name_min_values_present?
          Item.min_margin(search_params)
        else
          
        end
  end
  
      def name_value_present?
        search_params[:name].present? && !search_params[:max].present? && !search_params[:min].present?
      end
      
      def all_present?
        search_params[:name].present? && search_params[:max].present? && search_params[:min].present?
      end

      def min_max_values_present?
       search_params[:min].present? && search_params[:max].present? && !search_params[:name].present?
      end
        
      def name_max_values_present?
        search_params[:name].present? && search_params[:max].present?
      end
      
      def name_min_values_present?
        search_params[:name].present? && search_params[:min].present?
      end
        
        
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
    def index
        @items = Item.visible
        
    end
    
    def new
        @item = Item.new
    end
    
    def search
      #binding.pry
      @items = if none_present?
        Item.all
      else
        perform_search(search_params)
      end
      empty_item
    end
    
    def create
        @item = Item.new(item_params)
        if @item.save
            redirect_to @item
           # flash[:success] = "New item created."
        else
           # flash[:danger] = "Name can't be blank"
            render 'new'
        end
    end
    
    def show
       @item = find_item
    end
    
    def edit 
        @item = find_item
    end
    
    def update
        @item = find_item
        if @item.update_attributes(item_params)
            @item.save#it can update individually the params
            flash.now[:info] = "Item updated."
            redirect_to @item
        else
            flash.now[:danger] = "Invalid information."
            render 'edit'
        end
    end

    def destroy 
       @item = find_item 
       @item.delete
       redirect_to root_path
    end
    
    def hide
        @item = find_item
        @item.destroy
        redirect_to items_url
    end


    private
    
      def item_params
          params.require(:item).permit(:name, :price, :hidden, :add_to_basket)
      end
      
      def search_params
         params.require(:search_params).permit(:name, :min, :max) 
      end
      
      def find_item
         Item.visible.find(params[:id] ) 
      end
      
      def empty_item
        if @items.blank?
          flash[:warning] = "Couldn't find item.Sorry:("
          redirect_to items_path 
        end
      end
            
      def none_present?
        !search_params[:name].present? && !search_params[:max].present? && !search_params[:min].present?
      end

        
end

app/helpers/items_helper.rb
module ItemsHelper
    
  
  
end

app/views/items/_search.html.erb
<p>
<%= form_tag search_items_path, :method => 'get' do %>

  <p>
    Search <%= text_field_tag :name, params[:name] %>
   
    <%= submit_tag 'Search' %>
  </p>
<% end %>

</p>

app/views/items/edit.html.erb
<h1>Edit</h1>

<%= form_for @item do |f|   %>
<% if f.object.errors.any? %>
      <div id="error_explanation">
        <div class="alert alert-danger">
          The form contains <%= pluralize(f.object.errors.count, "error") %>.
        </div>
        <ul>
        <% f.object.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>    
    <%= f.label :name %>
    <%= f.text_field :name%>
    <%= f.label :price %>
    <%= f.text_field :price %>
    <%= f.submit %>
<% end %>

app/views/items/index.html.erb
<div class="container">
   <div class="row">
     <div class="col-xs-12">

<table class = "table table-bordered">
  <tr>
    <th>ID</th>
    <th>Name</th> 
    <th>Price</th>
    <th>Edit</th>
    <th>Delete</th>
    <th>Hide</th>
    <th>Add</th>
    <th>Bookmark</th>
  </tr>
  <% @items.each do |item| %>
      <tr>
        <td> <%= link_to item.id, item %> </td>
        <td> <%= item.name %> </td>
        <td> £ <%= item.price %> </td>
        <td> <%= link_to 'Edit', edit_item_path(item) %> </td>
        <td> <%= link_to 'Delete', item, method: :delete   %> </td>
        <td><%= link_to 'Hide', item, method: :hide %></td>
        <td> <%= link_to "Add to Basket", basket_items_path({item_id: item.id}), method: :post %> </td>
        <td><%= link_to 'Bookmark', bookmarks_path({item_id: item.id}), method: :post %></td>
      </tr>
    <% end %>

 
</table>
  
    </div>
  </div>
</div>
  
<%= link_to "New Items", new_item_path %>
<div>
  <%= form_for :search_params, url: search_items_path, method: :get do |f| %>
    Search <%= f.text_field :name %>
    Search min <%= f.text_field :min %>
    Search max <%= f.text_field :max %>
  <%= f.submit 'Search' %>
    
<% end %>

</div>

app/views/items/new.html.erb
<h1> New item </h1>



<%= form_for @item do |f|   %>
    <%= render 'shared/error_messages', obj: @item %>    
    <%= f.label :name %>
    <%= f.text_field :name%>
    <%= f.label :price %>
    <%= f.text_field :price %>
    <%= f.submit "Create new item", class: "btn btn-primary" %>
<% end %>

app/views/items/search.html.erb
<h3>Result</h3>
<table class = "table table-bordered">
    <tr>
        <th>Name</th> 
    </tr>
    
    <% @items.each do |item|%>
    
        <tr>
            <td><%= item.name %></td>
        </tr>
    <%end%>

  
</table>

app/views/items/show.html.erb
<dl>
    <dt>Name</dt>
    <dd><%= @item.name %></dd>
    
    <dt>Price</dt>
    <dd><%= @item.price %> </dd>
 </dl>
 
 
 <%= link_to 'Edit', edit_item_path(@item) %>
 <%= link_to 'Back', items_path, title: 'Back'%>
 