config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

   root 'static_pages#home'
   resources :items do
    collection do
     get 'search'
    end
   end
   
   resources :users
    get    '/login',   to: 'sessions#new'
    post   '/login',   to: 'sessions#create'
    delete '/logout',  to: 'sessions#destroy'

   resources :basket_items, only: [:create, :index, :destroy] 
   
   get '/basket', to: 'basket_items#index'
   
   resources :quotes, only: [:index, :create, :destroy]
   
   resources :bookmarks
 
 #  get '/search', to: 'search#run'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <title>
    Rails practice  
  </title>
  <head>

    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "Rails practice", '/' , id: "logo" %>
       
        <nav>
           
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home", '/' %></li>
            <% if logged_in? %>
              <li><%= link_to "Items", items_path %></li>
              <li><%= link_to "Quotes", quotes_path %></li>
              
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Account <b class="caret"></b>
                </a>
                  <ul class="dropdown-menu">
                    <li><%= link_to "Profile", current_user %></li>
                    <li><%= link_to "Basket", basket_path %></li>
                    <li><%= link_to "Bookmarks", bookmarks_path %></li>
                    <li><%= link_to "Logout", logout_path, method: :delete %></li>
                  </ul>
                </li>
              
              
              
            <% else%>
              <li><%= link_to "Login", login_path %></li>
              <li><%= link_to "SignUp", new_user_path %></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>

      <%= yield %>
      
    </div>
  </body>
</html>